# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-CSTA
version:      0.03
version_from: lib/Net/CSTA.pm
installdirs:  site
requires:
    Convert::ASN1:                 0.20
    MIME::Base64:                  0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
